#define FIRMWARE_BUILDDATE "2017-04-21 21:35:46"
#define FIRMWARE_REVISION L"4063"
#define REVISION_STR "Clover revision: 4063"
#define BUILDINFOS_STR "Args: -mc --no-usb -D NO_GRUB_DRIVERS_EMBEDDED -D CHECK_FLAGS -t XCODE8 | -D DISABLE_USB_SUPPORT -D NO_GRUB_DRIVERS_EMBEDDED -D CHECK_FLAGS -D USE_BIOS_BLOCKIO -D USE_LOW_EBDA -a X64 -b RELEASE -t XCODE8 -n 5 | OS: 10.12.5 | XCODE: 8.3.2"
